name: test src

on:
  push:
    branches:
      - master
      - develop

jobs:
  artisan_test:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: cronjob-alternative
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name : prepare for build
        shell: bash
        run : |
          cd ./src
          composer install  -q --no-ansi --no-interaction --no-scripts --no-progress
          composer dump-autoload
      - name: artisan test
        shell: bash
        run : |
          cd ./src
          touch database/database-testing.sqlite
          php artisan test
